language: python
python:
  - "2.7_with_system_site_packages"
  - "3.3"
  - "3.4"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy libatlas-dev liblapack-dev gfortran
    - sudo apt-get install -qq libpng12-dev libtiff4-dev libwebp-dev
    - sudo apt-get install -qq xcftools
    - pip install numpy
install:
    - make debug
script: nosetests
